apiVersion: v1
data:
  domain: 35.205.58.161.nip.io
  email: ""
  exposer: Ingress
  issuer: ""
  tls: "false"
  urltemplate: ""
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: ingress-config
